a = input('Digite algo: \n')
print('O tipo primitivo deste valor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?',a.isalnum())
print('Estão em maiúsulas?',a.isupper())
print('Estão em minúsculas?',a.islower())
print('Está capitalizado?', a.istitle())